packages:
  atuin:
    specfile_path: atuin.spec
    upstream_package_name: atuin
    downstream_package_name: atuin
    actions:
      # Note: in upstream, the License has to be fixed manually after rust2rpm is run
      # Copy from %cargo_license_summary in the build.log
      fix-spec-file:
        - sh -c 'tar -xf ${PACKIT_PROJECT_ARCHIVE}'
        - sh -c 'rust2rpm --vendor ./atuin-${PACKIT_PROJECT_VERSION}'
        # For this repo we manually sed to correct the file
        # TODO: find the bundled dependencies
        # - sh -c 'sed -i -znre "s|(SourceLicense:\s*)(.*)\n.*\n(License:\s*)# FIXME|\3\2|p" atuin.spec'
      create-archive:
        - spectool -g -s0 atuin.spec
        - sh -c 'echo v${PACKIT_PROJECT_VERSION}.tar.gz'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm atuin.spec

srpm_build_deps:
  - rust2rpm

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    owner: sramanujam
    project: atuin
    targets:
      - fedora-all
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
