packages:
  atuin:
    specfile_path: atuin.spec
    files_to_sync:
      - atuin.spec
      - .packit.yaml
      - rust2rpm.toml
    upstream_package_name: atuin
    downstream_package_name: atuin
    actions:
      create-archive:
        - spectool -g -s0 atuin.spec
        - sh -c 'echo v${PACKIT_PROJECT_VERSION}.tar.gz'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm atuin.spec

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    owner: sramanujam
    project: atuin
    targets:
      - fedora-all
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
