packages:
  atuin:
    specfile_path: rust-atuin.spec
    files_to_sync:
      - rust-atuin.spec
      - .packit.yaml
    upstream_package_name: atuin
    downstream_package_name: rust-atuin
    actions:
      create-archive:
        - spectool -g -s0 rust-atuin.spec
        - sh -c 'rust2rpm --vendor atuin ${PACKIT_PROJECT_VERSION}'
        - sh -c 'echo atuin-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm rust-atuin.spec

srpm_build_deps:
  - rust2rpm

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    owner: sramanujam
    project: atuin
    targets:
      - fedora-all
      - epel-9
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-9
