packages:
  atuin:
    specfile_path: atuin/atuin.spec
    files_to_sync:
      - atuin/atuin.spec
      - atuin/rust2rpm.toml
      - .packit.yaml
    upstream_package_name: atuin
    downstream_package_name: atuin
    actions:
      create-archive:
        - spectool -g -s0 atuin/atuin.spec
        - sh -c 'echo v${PACKIT_PROJECT_VERSION}.tar.gz'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm atuin/atuin.spec
  # Upstream is working on it:
  rust-argon2:
    # https://bugzilla.redhat.com/show_bug.cgi?id=2258880
    specfile_path: rust-argon2/rust-argon2.spec
    actions:
      create-archive:
        - spectool -g -s0 rust-argon2/rust-argon2.spec
        - sh -c 'echo argon2-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm rust-argon2/rust-argon2.spec
  rust-crypto_secretbox:
    # https://bugzilla.redhat.com/show_bug.cgi?id=2259330
    specfile_path: rust-crypto_secretbox/rust-crypto_secretbox.spec
    actions:
      create-archive:
        - spectool -g -s0 rust-crypto_secretbox/rust-crypto_secretbox.spec
        - sh -c 'echo crypto_secretbox-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm rust-crypto_secretbox/rust-crypto_secretbox.spec
  # Already upstream, needs update
  rust-axum:
    specfile_path: rust-axum/rust-axum.spec
    files_to_sync:
      - rust-axum/rust-axum.spec
      - rust-axum/rust2rpm.toml
    actions:
      create-archive:
        - spectool -g -s0 rust-axum/rust-axum.spec
        - sh -c 'echo axum-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm rust-axum/rust-axum.spec
  rust-rustls-pemfile:
    specfile_path: rust-rustls-pemfile/rust-rustls-pemfile.spec
    files_to_sync:
      - rust-rustls-pemfile/rust-rustls-pemfile.spec
      - rust-rustls-pemfile/rust2rpm.toml
    actions:
      create-archive:
        - spectool -g -s0 rust-rustls-pemfile/rust-rustls-pemfile.spec
        - sh -c 'echo rustls-pemfile-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm rust-rustls-pemfile/rust-rustls-pemfile.spec
  rust-tower-http:
    specfile_path: rust-tower-http/rust-tower-http.spec
    files_to_sync:
      - rust-tower-http/rust-tower-http.spec
      - rust-tower-http/rust2rpm.toml
    actions:
      create-archive:
        - spectool -g -s0 rust-tower-http/rust-tower-http.spec
        - sh -c 'echo tower-http-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm rust-tower-http/rust-tower-http.spec
  rust-typed-builder:
    specfile_path: rust-typed-builder/rust-typed-builder.spec
    files_to_sync:
      - rust-typed-builder/rust-typed-builder.spec
      - rust-typed-builder/rust2rpm.toml
    actions:
      create-archive:
        - spectool -g -s0 rust-typed-builder/rust-typed-builder.spec
        - sh -c 'echo typed-builder-${PACKIT_PROJECT_VERSION}.crate'
      get-current-version:
        - rpmspec -q --qf "%{Version}" --srpm rust-typed-builder/rust-typed-builder.spec

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    owner: sramanujam
    project: atuin
    targets:
      - fedora-all
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
