[features]
hide = [
    "__internal_happy_eyeballs_tests",
    "nightly",
]

[tests]
run = ["none"]
comments = [
    "examples and integration tests are not included in published crates",
    "tower dev-dependency is not packaged",
]
