# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate axum-extra

Name:           rust-axum-extra
Version:        0.9.3
Release:        %autorelease
Summary:        Extra utilities for axum

License:        MIT
URL:            https://crates.io/crates/axum-extra
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Extra utilities for axum.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-read-body-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-read-body-devel %{_description}

This package contains library source intended for building other packages which
use the "async-read-body" feature of the "%{crate}" crate.

%files       -n %{name}+async-read-body-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie" feature of the "%{crate}" crate.

%files       -n %{name}+cookie-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie-key-expansion-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie-key-expansion-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie-key-expansion" feature of the "%{crate}" crate.

%files       -n %{name}+cookie-key-expansion-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie-private-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie-private-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie-private" feature of the "%{crate}" crate.

%files       -n %{name}+cookie-private-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie-signed-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie-signed-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie-signed" feature of the "%{crate}" crate.

%files       -n %{name}+cookie-signed-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+erased-json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+erased-json-devel %{_description}

This package contains library source intended for building other packages which
use the "erased-json" feature of the "%{crate}" crate.

%files       -n %{name}+erased-json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+form-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+form-devel %{_description}

This package contains library source intended for building other packages which
use the "form" feature of the "%{crate}" crate.

%files       -n %{name}+form-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+json-deserializer-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+json-deserializer-devel %{_description}

This package contains library source intended for building other packages which
use the "json-deserializer" feature of the "%{crate}" crate.

%files       -n %{name}+json-deserializer-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+json-lines-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+json-lines-devel %{_description}

This package contains library source intended for building other packages which
use the "json-lines" feature of the "%{crate}" crate.

%files       -n %{name}+json-lines-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+multipart-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+multipart-devel %{_description}

This package contains library source intended for building other packages which
use the "multipart" feature of the "%{crate}" crate.

%files       -n %{name}+multipart-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+protobuf-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+protobuf-devel %{_description}

This package contains library source intended for building other packages which
use the "protobuf" feature of the "%{crate}" crate.

%files       -n %{name}+protobuf-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+query-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+query-devel %{_description}

This package contains library source intended for building other packages which
use the "query" feature of the "%{crate}" crate.

%files       -n %{name}+query-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+typed-header-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+typed-header-devel %{_description}

This package contains library source intended for building other packages which
use the "typed-header" feature of the "%{crate}" crate.

%files       -n %{name}+typed-header-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+typed-routing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+typed-routing-devel %{_description}

This package contains library source intended for building other packages which
use the "typed-routing" feature of the "%{crate}" crate.

%files       -n %{name}+typed-routing-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
